### PR TITLE
Respect iconAnchor in markers

### PR DESCRIPTION
**Pull request by schwanksta**
In reference to my talking to myself over here: https://github.com/mapbox/leaflet-image/issues/17, this patch should allow markers with a custom iconAnchor to appear correct in a leaflet-image'd map.

### CODE REVIEW

**Comment by schwanksta** [comment]
And @tmcw, I managed to merge your download-image branch of geojson.io with the gh-pages master. Once this patch to leaflet-image is merged in, you could enable image downloads on geojson.io if you wanted. I can submit a patch over there.

**Comment by tmcw** [comment]
Cool, could you fix this in `index.js`? `leaflet-image.js` is a generated file and is blown away when you run `make`.

Unfortunately the geojson.io image thing is blocked in the other way - leaflet-image relies on Leaflet's Canvas mode, and Leaflet.draw, the basic engine behind geojson.io, isn't compatible with Canvas mode. And Leaflet throws away the code for rendering with Canvas when it pops into SVG mode. Waiting on the Leaflet 0.8 release for that to change.

**Comment by schwanksta** [comment]
Got it in index.js

Interestingly, geojson.io appears to work for me using leaflet-image. Though @palewire reports a shape he drew disappeared in one of his tests.

**Comment by palewire** [comment]
The shape didn't disappear in the image, but in the main viewer after I captured an image and changed the zoom.

**Comment by schwanksta** [comment]
Hm, I created this map:
http://datadesk.github.io/geojson.io/#id=gist:anonymous/472d80382df278aa4d8b&map=14/34.0721/-118.2475

Downloaded an image, changed the zoom, all still there. In Chrome on Ubuntu. Guess it's just not stable. Looking forward to 0.8

-Ken Schwencke

**Comment by tmcw** [comment]
Ah yeah - it works on Chrome, but not elsewhere afaik

**Pull request merged**
