### PR TITLE
use dummy image when loadTile get 404

### PR DESCRIPTION
**Pull request by smellman**
for issue #4 
When loadTile get 404 error, try this:
- if layer has errorTileUrl, use this.
- if layer doesn't have errorTileUrl, use dummy canvas image.
- if request to errorTileUrl get 404 error, use dummy canvas image.

How about this patch?

### CODE REVIEW

**Comment by tmcw** [comment]
Sounds good, though I'm not sure that the background should be set, shouldn't blank tiles be transparent?

**Comment by smellman** [comment]
I commit to use transparent image.
No problem in my case. (using Leaflet.Draw)

**Comment by smellman** [comment]
I found a problem if map has _panes but don't have overlayPane.

**Comment by olingerc** [comment]
Hi,
I'm also being bitten by this bug. I have a background layer with country tiles on which I add density tiles but which are limited to the coutnry's frontiers. Everything outside gives me 404 messages and the image is not rendered at all.

I applyied this PR:
Now I get an image, but it has black zones although the black tiles actually are there? Cf attachments.
Image with layer containing missing tiles activated:
with_missing
Image with layer containing missing tiles hidden:
no_missing

P.S. The legend is added using svg.js, maybe this causes the black tiles? Although the second image does not have the problem.

**Pull request merged**
